### ISSUE TITLE
Availability of the data

### ISSUE THREAD

**Issue by xEnVrE** [paroj/ycbev#1]
Dear authors,

I am writing to know whether the data of the dataset is going to be released.

Thank you

**Comment by paroj** [comment]
https://github.com/paroj/ycbev/releases/tag/v1

**Comment by xEnVrE** [comment]
Thank you and thanks for [adding](https://github.com/paroj/ycbev/commit/0a91cc19edc13483643423e8830e1d8b9961fde1) a link in the `README.md`.
